apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app: delivery
spec:
  acme:
    email: qcodelabsllc@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - dns01:
          cloudflare:
            email: qcodelabsllc@gmail.com
            apiTokenSecretRef:
              name: cloudflare-dns-credentials
              key: api_token
---