apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: qwallet
type: Opaque
stringData:
  username: "quabynah"
  password: "YS8rUSINtLMTWi8y"
  database: "qwallet"
  admin-password: "YS8rUSINtLMTWi8y"
  repmgr-username: "quabynah"
  repmgr-password: "YS8rUSINtLMTWi8y"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: qwallet
type: Opaque
stringData:
  password: "sJNeeINuWKI7Gdc3"
---
apiVersion: v1
kind: Secret
metadata:
  name: server-credentials
  namespace: qwallet
type: Opaque
stringData:
  token_secret: "Qf10d159aWAL23a5739df23cb65deLET"
---
#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
